version: 2
jobs:
  build:
    docker:
      - image: python:3.5
        environment:
          FLASK_CONFIG: testing
          DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: postgres:9.5.5
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - shell:
          name: Install Yarn
          command: |
            apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
            echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
            apt-get update -qq
            apt-get install -y -qq yarn
      - cache_restore:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - shell:
          name: Install Dependencies
          command: |
            yarn
            pip install -r requirements.txt
      - cache_save:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "/home/ubuntu/.yarn-cache"
      - shell:
          name: Run Tests
          command: python manage.py test --coverage
      - store_artifacts:
          path: test-reports/coverage
          destination: reports
      - test_results_store:
          path: "test-reports/"
